### ISSUE TITLE
About adding new data to preprocessed files

### ISSUE THREAD

**Issue by kninomiya-mope** [gpertea/tiebrush#5]
Thank you for your great job!
This tool helps me a lot.

In your paper about tiebrush, you wrote, "Furthermore, the method is designed to recognize ‘tiebrushed’ files, allowing users to add data to preprocessed files efficiently." So I want to add multiple bam files to a file which was already processed by tiewrap command. 
In that case, how should I add them? Which is the appropriate way to do it?
1: process only new bam files by tiewrap command→ process the new tiewrapped file and the old tiewrapped  file by tiewrap command
2:process new bam files and the old tiewrapped file at once by tiewrap command

Thank you in advance.

**Comment by alevar** [comment]
Hi!

Thank you for using TieBrush! To answer your question, there should not be any difference in how files are added. Internally, when running large jobs, tiewrap will split files into batches and process each batch separately, producing multiple temporary tiebrushed files. Afterwards, individual temporary files are merged together to produce the final output. However the same can be achieved by adding unprocessed samples into tiebrushed files. You can test it using example data as follows:
1. tiewrap.py -o ./t1.all.bam t1/t1s0.bam t1/t1s1.bam t1/t1s2.bam t1/t1s3.bam t1/t1s4.bam t1/t1s5.bam t1/t1s6.bam t1/t1s7.bam t1/t1s8.bam t1/t1s9.bam
2. iewrap.py -o ./t1.1_8.bam t1/t1s0.bam t1/t1s1.bam t1/t1s2.bam t1/t1s3.bam t1/t1s4.bam t1/t1s5.bam t1/t1s6.bam t1/t1s7.bam t1/t1s8.bam && tiewrap.py -o ./t1.1_8p9.bam t1.1_8.bam t1/t1s9.bam
3. tiewrap.py -o ./t1.1_4.bam t1/t1s0.bam t1/t1s1.bam t1/t1s2.bam t1/t1s3.bam t1/t1s4.bam && tiewrap.py -o ./t1.5_9.bam t1/t1s5.bam t1/t1s6.bam t1/t1s7.bam t1/t1s8.bam t1/t1s9.bam && tiewrap.py -o ./t1.1_4p5_9.bam t1.1_4.bam t1.5_9.bam 

All three methods above should yield functionally identical output. The only expected differences in the output should be due to:
1. commands used to generate files are stored in the header will be different for each method above
2. the order of auxiliary tags is not guaranteed and can vary

I believe those are the only differences you should expect to see. If you notice any unexpected behaviors - please don't hesitate to let us know!

Hope this answers your questions! Thank you,

Ales

**Comment by kninomiya-mope** [comment]
Thank you very much for your kind reply!
I got it very well. I'll give it a try.
